sudo: required
language: node_js
node_js:
  - 'node'
dist: trusty
addons:
  firefox: "latest"
before_install:
    # Start a display server where all graphical operations happens in memory
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
